### ISSUE TITLE
Creating users is broken

### ISSUE THREAD

**Issue by kohler** [kohler/peteramati#22]

**Comment by ms705** [comment]
Still seems to be broken!

Here's what I get when trying to create a new account:
```[Mon May 20 13:16:21.198432 2019] [php7:error] [pid 3493] [client 18.26.5.159:46606] PHP Fatal error:  Uncaught Error: Call to undefined method Contact::save_json() in peteramati/src/contact.php:880
Stack trace:
#0 peteramati/lib/login.php(241): Contact::create(Object(Conf), Object(stdClass))
#1 peteramati/lib/login.php(127): LoginHelper::create_account(NULL, NULL)
#2 peteramati/lib/login.php(71): LoginHelper::login()
#3 peteramati/pages/home.php(42): LoginHelper::check_login()
#4 peteramati/index.php(35): require_once('...')
#5 {main}
  thrown in peteramati/src/contact.php on line 880, referer: http://.../testclass/?post=0kg9b2d41esb
```
Grepping through the code, there is no implementation of `save_json` anywhere, although one does exist in HotCRP. Does that need porting over?

(In the event, I solved the problem by inserting users into the database manually, but I'd like to know if I'm missing something or this is known breakage.)
